{
 "title": "P4 Stats (no SDP)",
 "description": "Perforce Helix Core server stats. Relies on P4Prometheus and related scripts to collect data from your Commit/Edge/Replica servers.\n",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "serverid", "label": "ServerID", "query": "label_values(serverid)" }
  ]
 },
 "panels": [
  { "title": "Monitor Tracking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Monitor Processes (by cmd)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "p4_monitor_by_cmd{serverid=\"$serverid\"}",
     "legendFormat": "p4_monitor_by_cmd{serverid=\"{{serverid}}\",cmd=\"{{cmd}}\"}"
    },
    {
     "expr": "sum(p4_monitor_by_cmd{serverid=\"$serverid\"})"
    }
   ]
  },
  {
   "title": "Monitor Processes (by user)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "p4_monitor_by_user{serverid=\"$serverid\"}",
     "legendFormat": "p4_monitor_by_user{serverid=\"{{serverid}}\",user=\"{{user}}\"}"
    },
    {
     "expr": "sum(p4_monitor_by_user{serverid=\"$serverid\"})"
    }
   ]
  },
  {
   "title": "$serverid uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p4_server_uptime{serverid=\"$serverid\"}"
    }
   ]
  },
  {
   "title": "p4d log lines read (rate/min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "rate(p4_prom_log_lines_read{serverid=\"$serverid\"}[1m])"
    }
   ]
  },
  {
   "title": "All P4 Cmds Count (rate/10min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(p4_completed_cmds_per_day{serverid=\"$serverid\"}[10m])"
    },
    {
     "expr": "sum(rate(p4_cmd_counter{serverid=\"$serverid\"}[10m]))"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Replica Journal number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "p4_replica_curr_jnl{serverid=\"$serverid\"}",
     "legendFormat": "p4_replica_curr_jnl - {{servername}}"
    }
   ]
  },
  {
   "title": "Replica Journal Pos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "p4_replica_curr_pos{serverid=\"$serverid\"}",
     "legendFormat": "p4_replica_curr_jnl - {{servername}}"
    }
   ]
  },
  {
   "title": "Pull queue size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expr": "p4_pull_queue{}", "legendFormat": "p4_pull_queue - {{serverid}}" }
   ]
  },
  {
   "title": "Pull queue errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    { "expr": "p4_pull_errors{}", "legendFormat": "p4_pull_queue - {{serverid}}" }
   ]
  },
  { "title": "Cmd Count and Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Cmds duration (rate/min)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "topk(10,rate(p4_cmd_cumulative_seconds{serverid=\"$serverid\"}[1m]))",
     "legendFormat": "{cmd=\"{{cmd}}\",serverid=\"{{serverid}}\"}}"
    }
   ]
  },
  {
   "title": "p4 cmds top 10 (rate/min)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum without (instance, job)(topk(10,rate(p4_cmd_counter{serverid=\"$serverid\"}[1m])))"
    }
   ]
  },
  { "title": "Table Locking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "p4 read locks held per table (rate/min)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum without (instance, job)(topk(10,rate(p4_total_read_held_seconds{serverid=\"$serverid\"}[1m])))"
    }
   ]
  },
  {
   "title": "p4 read locks waiting (rate/min)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum without (instance, job)(topk(10,rate(p4_total_read_wait_seconds{serverid=\"$serverid\"}[1m])))"
    }
   ]
  },
  {
   "title": "p4 write locks held per table (rate/min)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "sum without (instance, job)(topk(10,rate(p4_total_write_held_seconds{serverid=\"$serverid\"}[1m])))"
    }
   ]
  },
  {
   "title": "p4 write locks wait per table (rate/min)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "sum without (instance, job)(topk(10,rate(p4_total_write_wait_seconds{serverid=\"$serverid\"}[1m])))"
    }
   ]
  },
  { "title": "Health Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "p4metrics collector health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p4_monitoring_up{serverid=\"$serverid\"}"
    }
   ]
  },
  {
   "title": "License time remaining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p4_license_time_remaining{serverid=\"$serverid\"}"
    }
   ]
  },
  {
   "title": "SSL certificate time remaining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p4_ssl_cert_expires{serverid=\"$serverid\"} - time()"
    }
   ]
  },
  {
   "title": "Blocked processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p4_locks_cmds_blocked{serverid=\"$serverid\"}"
    }
   ]
  }
 ]
}