#!/usr/bin/env python3
"""Generate Go lookup map for Perforce error short names.

Parses:
- all_errors.txt entries containing ErrorOf( ES_*, <subcode>, ... )
- errornum.h subsystem enum values (ES_* -> int)

Outputs a Go map keyed by [2]int{subsys, subcode} with values like CL_LockCheckFail.
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
from pathlib import Path

ENTRY_RE = re.compile(
    r"ErrorId\s+Msg([A-Za-z0-9_]+)::([A-Za-z0-9_]+)\s*=\s*\{\s*ErrorOf\(\s*(ES_[A-Z0-9_]+)\s*,\s*(\d+)",
)
SUBSYS_RE = re.compile(r"\b(ES_[A-Z0-9_]+)\s*=\s*(\d+)\b")

def parse_subsystems(text: str) -> dict[str, int]:
    out: dict[str, int] = {}
    for name, value in SUBSYS_RE.findall(text):
        out[name] = int(value)
    return out


def subsystem_prefix(es_name: str) -> str:
    if es_name.startswith("ES_"):
        return es_name[3:]
    return es_name


def parse_entries(text: str, subsystems: dict[str, int]) -> tuple[dict[tuple[int, int], str], int]:
    out: dict[tuple[int, int], str] = {}
    dup_count = 0

    for m in ENTRY_RE.finditer(text):
        _msg_group = m.group(1)
        symbol = m.group(2)
        es_name = m.group(3)
        subcode = int(m.group(4))

        subsys = subsystems.get(es_name)
        if subsys is None:
            continue

        prefix = subsystem_prefix(es_name)
        short_name = f"{prefix}_{symbol}"
        key = (subsys, subcode)

        # Keep the first encountered symbol for a given (subsys, subcode).
        if key in out:
            dup_count += 1
            continue
        out[key] = short_name

    return out, dup_count


def render_go(lookup: dict[tuple[int, int], str], source_errors: Path, source_header: Path, dup_count: int) -> str:
    ts = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()
    lines: list[str] = []
    lines.append("package main")
    lines.append("")
    lines.append("// Code generated by generate_error_lookup_go.py; DO NOT EDIT.")
    lines.append(f"// Sources: {source_errors.name}, {source_header.name}")
    lines.append(f"// Generated: {ts}")
    lines.append(f"// Duplicate (subsys, subcode) definitions skipped: {dup_count}")
    lines.append("")
    lines.append("var generatedErrorShortBySubsysSubcode = map[[2]int]string{")

    for (subsys, subcode), short in sorted(lookup.items()):
        lines.append(f'\t{{{subsys}, {subcode}}}: "{short}",')

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Go short-name lookup map from all_errors + errornum.h")
    parser.add_argument("--errors", required=True, help="Path to all_errors.txt")
    parser.add_argument("--errornum", required=True, help="Path to errornum.h")
    parser.add_argument("--out", required=True, help="Output Go file path")
    args = parser.parse_args()

    errors_path = Path(args.errors)
    errornum_path = Path(args.errornum)
    out_path = Path(args.out)

    subsystems = parse_subsystems(errornum_path.read_text(encoding="utf-8", errors="replace"))
    lookup, dup_count = parse_entries(errors_path.read_text(encoding="utf-8", errors="replace"), subsystems)
    go_text = render_go(lookup, errors_path, errornum_path, dup_count)
    out_path.write_text(go_text, encoding="utf-8")


if __name__ == "__main__":
    main()
