#!/usr/bin/env python3
"""Generate Go error CSV schema mappings from full p4 logschema output.

Input format expects p4 logschema -Aa records like:
... f_recordType 4
... f_recordVersion 58
... f_recordName Error
... f_field 12
... f_name f_prog

"""

from __future__ import annotations

import argparse
import datetime as dt
import re
from dataclasses import dataclass, field
from pathlib import Path


LINE_RE = re.compile(r"^\.\.\.\s+(\w+)\s+(.*)$")


@dataclass
class Schema:
    record_type: int
    record_version: int
    record_name: str
    fields: dict[str, int] = field(default_factory=dict)

    @property
    def field_count(self) -> int:
        if not self.fields:
            return 0
        return max(self.fields.values()) + 1


def is_error_record_name(record_name: str) -> bool:
    return "error" in record_name.lower()


def parse_errschema(text: str) -> list[Schema]:
    entries: dict[tuple[int, int, str], Schema] = {}
    current = {
        "f_recordType": None,
        "f_recordVersion": None,
        "f_recordName": None,
        "f_field": None,
        "f_name": None,
    }

    for raw in text.splitlines():
        line = raw.strip()
        if not line or line == "--":
            continue
        m = LINE_RE.match(line)
        if not m:
            continue
        key, value = m.group(1), m.group(2)
        current[key] = value

        if key != "f_name":
            continue

        if not all(current[k] is not None for k in ("f_recordType", "f_recordVersion", "f_recordName", "f_field", "f_name")):
            continue

        rtype = int(current["f_recordType"])
        rver = int(current["f_recordVersion"])
        rname = str(current["f_recordName"])
        fidx = int(current["f_field"])
        fname = str(current["f_name"])

        # Keep only error-family records from full logschema output.
        if not is_error_record_name(rname):
            continue

        schema_key = (rtype, rver, rname)
        schema = entries.get(schema_key)
        if schema is None:
            schema = Schema(record_type=rtype, record_version=rver, record_name=rname)
            entries[schema_key] = schema
        schema.fields[fname] = fidx

    schemas = list(entries.values())
    schemas.sort(key=lambda s: (s.field_count, s.record_name, s.record_version, s.record_type))
    return schemas


def go_map_literal(fields: dict[str, int]) -> str:
    keys = sorted(fields.keys())
    parts = [f'"{k}": {fields[k]},' for k in keys]
    joined = "\n\t\t\t".join(parts)
    return "map[string]int{\n\t\t\t" + joined + "\n\t\t}"


def render_go(schemas: list[Schema], source_path: Path) -> str:
    ts = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()
    lines: list[str] = []
    lines.append("package main")
    lines.append("")
    lines.append("// Code generated by generate_errschema_go.py; DO NOT EDIT.")
    lines.append(f"// Source: {source_path.name}")
    lines.append(f"// Generated: {ts}")
    lines.append("")
    lines.append("type errorCSVSchema struct {")
    lines.append("\tRecordType    int")
    lines.append("\tRecordVersion int")
    lines.append("\tRecordName    string")
    lines.append("\tFieldCount    int")
    lines.append("\tFieldIndex    map[string]int")
    lines.append("}")
    lines.append("")
    lines.append("var generatedErrorCSVSchemas = []errorCSVSchema{")
    for s in schemas:
        lines.append("\t{")
        lines.append(f"\t\tRecordType: {s.record_type},")
        lines.append(f"\t\tRecordVersion: {s.record_version},")
        lines.append(f"\t\tRecordName: \"{s.record_name}\",")
        lines.append(f"\t\tFieldCount: {s.field_count},")
        lines.append(f"\t\tFieldIndex: {go_map_literal(s.fields)},")
        lines.append("\t},")
    lines.append("}")
    lines.append("")
    lines.append("var generatedErrorCSVByFieldCount = buildErrorCSVSchemaByFieldCount(generatedErrorCSVSchemas)")
    lines.append("")
    lines.append("func buildErrorCSVSchemaByFieldCount(schemas []errorCSVSchema) map[int]errorCSVSchema {")
    lines.append("\tout := make(map[int]errorCSVSchema)")
    lines.append("\tfor _, s := range schemas {")
    lines.append("\t\tbest, ok := out[s.FieldCount]")
    lines.append("\t\tif !ok || schemaRank(s) > schemaRank(best) {")
    lines.append("\t\t\tout[s.FieldCount] = s")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("\treturn out")
    lines.append("}")
    lines.append("")
    lines.append("func schemaRank(s errorCSVSchema) int {")
    lines.append("\trecordBonus := 0")
    lines.append("\tswitch s.RecordName {")
    lines.append("\tcase \"Error\":")
    lines.append("\t\trecordBonus = 30")
    lines.append("\tcase \"FatalError\":")
    lines.append("\t\trecordBonus = 20")
    lines.append("\tcase \"AnyError\":")
    lines.append("\t\trecordBonus = 10")
    lines.append("\t}")
    lines.append("\treturn s.RecordVersion*100 + recordBonus")
    lines.append("}")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Go error schema from p4 logschema -Aa output")
    parser.add_argument("--in", dest="infile", required=True, help="Input logschema text file (full p4 logschema -Aa output)")
    parser.add_argument("--out", dest="outfile", required=True, help="Output Go file")
    args = parser.parse_args()

    infile = Path(args.infile)
    outfile = Path(args.outfile)

    schemas = parse_errschema(infile.read_text(encoding="utf-8"))
    go_text = render_go(schemas, infile)
    outfile.write_text(go_text, encoding="utf-8")


if __name__ == "__main__":
    main()
