{
 "title": "P4 Stats",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "name",
    "label": "Host:",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_uname_info{nodename=\"$name\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(node_uname_info{instance=~\"$node:(.*)\"}, instance)"
   },
   { "name": "sdpinst", "label": "SDPInstance", "query": "label_values(sdpinst)" },
   { "name": "serverid", "label": "ServerID", "query": "label_values(serverid)" }
  ]
 },
 "panels": [
  { "title": "Monitor Tracking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Monitor Processes (by cmd)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "p4_monitor_by_cmd{sdpinst=\"$sdpinst\",serverid=\"$serverid\"}",
     "legendFormat": "p4_monitor_by_cmd{serverid=\"{{serverid}}\",cmd=\"{{cmd}}\"}"
    },
    {
     "expr": "sum(p4_monitor_by_cmd{sdpinst=\"$sdpinst\",serverid=\"$serverid\"})"
    }
   ]
  },
  {
   "title": "Monitor Processes (by user)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "p4_monitor_by_user{sdpinst=\"$sdpinst\",serverid=\"$serverid\"}",
     "legendFormat": "p4_monitor_by_user{serverid=\"{{serverid}}\",user=\"{{user}}\"}"
    },
    {
     "expr": "sum(p4_monitor_by_user{sdpinst=\"$sdpinst\",serverid=\"$serverid\"})"
    }
   ]
  },
  {
   "title": "$serverid uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 13 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "p4_server_uptime{sdpinst=\"$sdpinst\",serverid=\"$serverid\"}"
    }
   ]
  },
  {
   "title": "$serverid time since last checkpoint",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 13 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - p4_sdp_checkpoint_log_time{sdpinst=\"$sdpinst\",serverid=\"$serverid\"}"
    }
   ]
  },
  {
   "title": "$serverid time since last checkpoint (alert)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 10, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "time() - p4_sdp_checkpoint_log_time{sdpinst=\"$sdpinst\",serverid=\"$serverid\"}"
    }
   ]
  },
  {
   "title": "$serverid Time for last checkpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "p4_sdp_checkpoint_duration{sdpinst=\"$sdpinst\",serverid=\"$serverid\"}"
    }
   ]
  },
  {
   "title": "p4d log lines read (rate/min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(p4_prom_log_lines_read{sdpinst=\"$sdpinst\",serverid=\"$serverid\"}[1m])"
    }
   ]
  },
  {
   "title": "All P4 Cmds Count (rate/10min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(p4_completed_cmds_per_day{instance=\"p4poke-chi:9100\",sdpinst=\"$sdpinst\",serverid=\"$serverid\"}[10m])"
    },
    {
     "expr": "sum(rate(p4_cmd_counter{sdpinst=\"$sdpinst\",serverid=\"$serverid\"}[10m]))"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Replica Journal number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "p4_replica_curr_jnl{sdpinst=\"$sdpinst\",serverid=\"$serverid\"}",
     "legendFormat": "p4_replica_curr_jnl - {{servername}}"
    }
   ]
  },
  {
   "title": "Replica Journal Pos",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "p4_replica_curr_pos{sdpinst=\"$sdpinst\",serverid=\"$serverid\"}",
     "legendFormat": "p4_replica_curr_jnl - {{servername}}"
    }
   ]
  },
  {
   "title": "Pull queue size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "p4_pull_queue{sdpinst=\"$sdpinst\"}",
     "legendFormat": "p4_pull_queue - {{serverid}}"
    }
   ]
  },
  {
   "title": "Pull queue errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "p4_pull_errors{sdpinst=\"$sdpinst\"}",
     "legendFormat": "p4_pull_queue - {{serverid}}"
    }
   ]
  },
  {
   "title": "Cmd Count and Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true
  },
  {
   "title": "Cmds duration (rate/min)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(p4_cmd_cumulative_seconds{sdpinst=\"$sdpinst\",serverid=\"$serverid\"}[1m]))",
     "legendFormat": "{cmd=\"{{cmd}}\",serverid=\"{{serverid}}\"}}"
    }
   ]
  },
  {
   "title": "p4 cmds top 10 (rate/min)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, job)(topk(10,rate(p4_cmd_counter{sdpinst=\"$sdpinst\",serverid=\"$serverid\"}[1m])))"
    }
   ]
  },
  { "title": "Table Locking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "p4 read locks held per table (rate/min)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, job)(topk(10,rate(p4_total_read_held_seconds{sdpinst=\"$sdpinst\",serverid=\"$serverid\"}[1m])))"
    }
   ]
  },
  {
   "title": "p4 read locks waiting (rate/min)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, job)(topk(10,rate(p4_total_read_wait_seconds{sdpinst=\"$sdpinst\",serverid=\"$serverid\"}[1m])))"
    }
   ]
  },
  {
   "title": "p4 write locks held per table (rate/min)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, job)(topk(10,rate(p4_total_write_held_seconds{sdpinst=\"$sdpinst\",serverid=\"$serverid\"}[1m])))"
    }
   ]
  },
  {
   "title": "p4 write locks wait per table (rate/min)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, job)(topk(10,rate(p4_total_write_wait_seconds{sdpinst=\"$sdpinst\",serverid=\"$serverid\"}[1m])))"
    }
   ]
  }
 ]
}